### ISSUE TITLE
spring boot 2.0.1 migration issue.

### ISSUE THREAD

**Issue by mkmyla** [ff4j/ff4j#305]
After migrating to spring boot 2.0.1 version, i started getting below error

Caused by: java.io.FileNotFoundException: class path resource [org/springframework/boot/web/support/SpringBootServletInitializer.class] cannot be opened because it does not exist

upon checking the issue could be because of wrong import in  `FF4JWebConfiguration` for SpringBootServletInitializer

Is there a version of ff4j compatible with spring boot 2.0.1  I am using latest ff4j version 1.7.1

**Comment by paul58914080** [comment]
Hello,

This is because `SpringBootServletInitializer` was moved to a different classpath in spring boot 2.x ` org.springframework.boot.web.**servlet**.support.SpringBootServletInitializer`than it used to be in spring boot 1.5.x. `org.springframework.boot.web.support.SpringBootServletInitializer`

As a workaround you could try to [exclude](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-auto-configuration.html)  `FF4JWebConfiguration` from autoconfiguration and write a similar configuration with the import path of `SpringBootServletInitializer` pointing to the new classpath as defined by spring boot 2.x

I have already started upgrading the ff4j-spring-boot-starter to spring boot 2.x and kotlin and should be released as part of 2.0.RC1

**Comment by mkmyla** [comment]
Thank you for reply. Will wait for 2.0.RC1

**Comment by Stellka24** [comment]
Hi, 
Any ETC for 2.0RC1?
Thanks.

**Comment by paul58914080** [comment]
Hello,

Mostly I have fixed the broken code

https://github.com/paul58914080/ff4j-spring-boot-starter-parent

I would have to integrate it as part of  ff4j version 2.

@clun any thoughts about the 2.0RC1 ?

**Comment by jorgerod** [comment]
Hello,

Any ETC for 2.0RC1?

Thanks.

**Comment by dvelopp** [comment]
Hello, any updates on this? Do you support Spring Boot 2 with its SpringBootServletInitializer moved to another package?

**Comment by paul58914080** [comment]
Started with the movement https://github.com/ff4j/ff4j-spring-boot-starter-parent.

Will try to release a RC (ReleaseCanditate) version within this week.

**Comment by drizztguen77** [comment]
Any ETC on the 2.0RC1? We are using Spring Boot 2 and really want to use FF4J but will have to choose something else if I can't get it working with Spring Boot 2 soon.

**Comment by xucw** [comment]
Hi Paul, any updates on the RC version ? and when will the RC version release? thanks.

**Comment by paul58914080** [comment]
Planning to release it next week.

**Comment by drizztguen77** [comment]
I tried following the changes explained by following [gist](https://gist.github.com/paul58914080/d8c9d4263438eb06545ffa8eedd2aac1)
The only change I made was I used FF4jDispatcherServlet instead of ConsoleServlet to get the new UI. It starts up fine but when I hit the URL it gets the following exception:

Receiver class org.ff4j.web.thymeleaf.CustomMessageResolver does not define or inherit an implementation of the resolved method abstract resolveMessage(Lorg/thymeleaf/context/ITemplateContext;Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String; of interface org.thymeleaf.messageresolver.IMessageResolver.
java.lang.AbstractMethodError: Receiver class org.ff4j.web.thymeleaf.CustomMessageResolver does not define or inherit an implementation of the resolved method abstract resolveMessage(Lorg/thymeleaf/context/ITemplateContext;Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String; of interface org.thymeleaf.messageresolver.IMessageResolver.

I have the thymeleaf dependency defined in my pom file.

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>

Any ideas what I can do to get this to work?

**Comment by paul58914080** [comment]
There has been a lot of breaking changes after the updates from spring-boot 2.x. 

I have decided that I will be removing the support of auto-configuration of the console which uses old dependencies and is causing a lot of conflicts with spring-boot 2.x.

To help you resolve the configuration, I have updated the [sample project]( https://github.com/ff4j/ff4j-spring-boot-starter-parent/tree/master/ff4j-spring-boot-sample)

In the **SpringBootApplication** I had to exclude the ThymeleafAutoConfiguration. [Refer](https://github.com/ff4j/ff4j-spring-boot-starter-parent/blob/master/ff4j-spring-boot-sample/src/main/java/org/ff4j/sample/Application.java#L25)

```java
@SpringBootApplication(exclude = ThymeleafAutoConfiguration.class)
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```

The following **dependencies** were added explicitly

```xml
        <dependency>
            <groupId>org.ff4j</groupId>
            <artifactId>ff4j-web</artifactId>
            <version>1.7.3</version>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
            <version>2.1.4.RELEASE</version>
        </dependency>
```

The [FF4JWebConfiguration.java](https://github.com/ff4j/ff4j-spring-boot-starter-parent/blob/master/ff4j-spring-boot-sample/src/main/java/org/ff4j/sample/config/FF4JWebConfiguration.java)

```java
@Configuration
@ConditionalOnClass({ConsoleServlet.class, FF4jDispatcherServlet.class})
@AutoConfigureAfter(FF4JConfiguration.class)
public class FF4JWebConfiguration extends SpringBootServletInitializer {

    @Bean
    public ServletRegistrationBean servletRegistrationBean(ConsoleServlet ff4jConsoleServlet) {
        return new ServletRegistrationBean(ff4jConsoleServlet, "/ff4j-console");
    }

    @Bean
    @ConditionalOnMissingBean
    public ConsoleServlet getFF4jServlet(FF4j ff4j) {
        ConsoleServlet ff4jConsoleServlet = new ConsoleServlet();
        ff4jConsoleServlet.setFf4j(ff4j);
        return ff4jConsoleServlet;
    }

    @Bean
    public ServletRegistrationBean ff4jDispatcherServletRegistrationBean(FF4jDispatcherServlet ff4jDispatcherServlet) {
        return new ServletRegistrationBean(ff4jDispatcherServlet, "/ff4j-web-console/*");
    }

    @Bean
    @ConditionalOnMissingBean
    public FF4jDispatcherServlet getFF4jDispatcherServlet(FF4j ff4j) {
        FF4jDispatcherServlet ff4jConsoleServlet = new FF4jDispatcherServlet();
        ff4jConsoleServlet.setFf4j(ff4j);
        return ff4jConsoleServlet;
    }
}
```

Let me know if this helps.

**Comment by drizztguen77** [comment]
That did the trick. I couldn't use ff4j-spring-boot-starter still with spring boot 2 but I did get it working without the starter. Thank you very much for your help.

**Comment by paul58914080** [comment]
Hello,

Please use the latest release i.e. 1.8.

The [sample project](https://github.com/ff4j/ff4j-spring-boot-starter-parent/tree/master/ff4j-spring-boot-sample) has also be updated.

> **Please note:** With the release of 1.8 the support of web console auto-configuration  it not supported. How I have demonstrated the usage in the [sample](https://github.com/ff4j/ff4j-spring-boot-starter-parent/blob/master/ff4j-spring-boot-sample/src/main/java/org/ff4j/sample/config/FF4JWebConfiguration.java)

**Comment by paul58914080** [comment]
Fixed with https://github.com/ff4j/ff4j-spring-boot-starter-parent/releases/tag/1.8
