### ISSUE TITLE
Web console: handle carriage return in feature description

### ISSUE THREAD

**Issue by fcornuau** [ff4j/ff4j#341]
Hello,

After defining a Feature with a description containing a carriage return (\n), it is not possible to edit it from the web console...

In fact, when clicking on the edit button of such feature, the console API returns the feature in JSON format but the Javascript raises the following parsing error:
`SyntaxError: JSON.parse: bad control character in string literal at line 1 column 54 of the JSON data
{"uid":"myFeature","enable":false,"description":"desc line1`
`desc line2","group":null,"permissions":[],"flippingStrategy":null,"customProperties":{}}`
and all the fields in the feature modal view are blank :-(.

Is-it possible to improve the Feature JSon parsing (write & read) to escape/unescape carriage returns and avoid such issue?

**Comment by clun** [comment]
This character will lead to issue in the parsing later on.

**Comment by Sleepy78** [comment]
Dear @clun ,
I am sorry I don't understand the meaning of "wontfix" ? 

If a user writes a description with a carriage return (meaning the user press "enter" while writing his feature description), and then when he tries to edit the feature he cannot even modify the feature description because of this character, this seems clearly to be a bug.
Thank you to reconsider.

Best regards,
Aurélien
