### ISSUE TITLE
Race condition in InMemoryState

### ISSUE THREAD

**Issue by kubked** [ff4j/ff4j#342]
Hi, I have met the same issue with version 1.6.5. Please look at the attached stacktrace:
```
org.ff4j.exception.FeatureAlreadyExistException: featureName already exist in store, duplicate uid
	at org.ff4j.store.AbstractFeatureStore.assertFeatureNotExist(AbstractFeatureStore.java:291)
	at org.ff4j.store.InMemoryFeatureStore.create(InMemoryFeatureStore.java:138)
	at org.ff4j.FF4j.getFeature(FF4j.java:432)
	at org.ff4j.FF4j.check(FF4j.java:177)
	at org.ff4j.FF4j.check(FF4j.java:164)
```

I see you removed ```synchronized``` in commit [```e1f7a72fe518603d93a713805cb801aa7e3532c6```.](https://github.com/ff4j/ff4j/commit/e1f7a72fe518603d93a713805cb801aa7e3532c6#diff-d9709a46f9cc2d52fa38101233089ba6L420) Is there a chance to get it back, please?

_Originally posted by @kubked in https://github.com/ff4j/ff4j/issues/121#issuecomment-467429608_

**Comment by mariusz-zawadzki** [comment]
I'm getting similar issue when using FF4j with autocreate = true and InMemoryFeatureStore

For multithreaded tests I used code like this:

        InMemoryFeatureStore fbs = new InMemoryFeatureStore() {

            @Override
            public void create(
                Feature fp) {
                try {
                    super.create(fp);
                } catch (FeatureAlreadyExistException alreadyExists) {
                    // poor mans concurrency handling
                    // ignoring if exists
                }
            }
        };

Adding 'synchronized' for getters in my oppinion is not a good idea because for most of the cases it can be called concurrently. 

Id suggest syncronization only the parts that are called when autocreate==true or poor mans concurrency handling as above.

**Comment by mariusz-zawadzki** [comment]
I've created a pull request with a fix for this issue:
https://github.com/ff4j/ff4j/pull/367

**Comment by clun** [comment]
Merged and delivered.
