### ISSUE TITLE
DynamoDB billing mode is hardcoded to Provisioned

### ISSUE THREAD

**Issue by cablespaghetti** [ff4j/ff4j#378]
https://github.com/ff4j/ff4j/blob/31a5847c87bce58663066f0c404befee85e66507/ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/feature/FeatureDynamoDBClient.java#L202

Since the new [On Demand billing mode](https://aws.amazon.com/blogs/aws/amazon-dynamodb-on-demand-no-capacity-planning-and-pay-per-request-pricing/) came out last year, it is usually preferable to use it over the old Provisioned mode. It would be good to have the option to use it when creating tables with ff4j, and maybe even have it as the default.

**Comment by cablespaghetti** [comment]
@jeromevdl I wondered if you had any thoughts on this.

I was looking at implementing this and sending over a PR, but I wasn't sure which approach would be best.

- Make it an option and add some new constructors to the already long list in FeatureStore/PropertyStoreDynamoDB
- Change the existing constructors in FeatureStore/PropertyStoreDynamoDB, which would break backwards compatibility but make the code cleaner
- Just hardcode it to On Demand

**Comment by jeromevdl** [comment]
> I was looking at implementing this and sending over a PR, but I wasn't sure which approach would be best.
> 
> Make it an option and add some new constructors to the already long list in FeatureStore/PropertyStoreDynamoDB
> Change the existing constructors in FeatureStore/PropertyStoreDynamoDB, which would break backwards compatibility but make the code cleaner
> Just hardcode it to On Demand

I think none of these. We should take it from external properties. Create a property file to put in the classpath. If the file is present, use it, otherwise use default (provisioned throughput). 

I agree there are already too many constructors. We should remove (only deprecate for the moment) the one with table name, and put that table name in the property file, with the billing mode.

Same thing for the property store...

```
ff4j.store.dynamodb.feature.tablename=<string>
ff4j.store.dynamodb.feature.billing=[PROVISIONED, PAY_PER_REQUEST] *
ff4j.store.dynamodb.feature.billing.rcu=<int> (optional, only for provisioned)
ff4j.store.dynamodb.feature.billing.wcu=<int> (optional, only for provisioned)

ff4j.store.dynamodb.property.tablename=<string>
ff4j.store.dynamodb.property.billing=[PROVISIONED, PAY_PER_REQUEST] *
ff4j.store.dynamodb.property.billing.rcu=<int> (optional, only for provisioned)
ff4j.store.dynamodb.property.billing.wcu=<int> (optional, only for provisioned)
```

Or we could even go further and give the ability to use a full json file (like [this one](https://github.com/ff4j/ff4j/blob/master/ff4j-store-aws-dynamodb/src/main/config/create-feature-dynamodb-table.json)), with constraints on attributes and indexes, but let the rest open... But, we cannot just pass the json to the java code. We would need to parse it and create a request, which is not good.

What do you think?

*: https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-billingmode

**Comment by cablespaghetti** [comment]
Sorry for the slow reply. This is outside my very limited Java knowledge I'm afraid. I'll have to leave this to someone else to implement.

**Comment by jeromevdl** [comment]
I have modified the code and created a pull request: https://github.com/ff4j/ff4j/pull/381, waiting for @clun to accept it (or not...)

**Comment by clun** [comment]
Was a bit over the world, will have a look to PR and release
