### ISSUE TITLE
how to logout a web console

### ISSUE THREAD

**Issue by wuhuanxing** [ff4j/ff4j#426]
hello ff4j,
I've read the whole wiki but , I could not find the way to logout a web console, seems no logout button on pages . I 've secure the web console with spring security and config the username/password in appcation.yml ,  like : https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-secured-console

**Comment by clun** [comment]
Hello,

The servlet `FF4j` itself does not handle authentication, your application does. 

In the sample you like I setup spring-security to protect the URL with `HTTP Basic authentication`, this is not a login page and as such there is no logout.

You can change this behaviour by replacing code in `FF4jWebConsoleSecure`.

```java
protected void configure(HttpSecurity http) throws Exception {
 LOGGER.info("Securing the webconsole access as property 'ff4j.webconsole.secure' is true");
 http.authorizeRequests()
        .antMatchers("/").permitAll()
        .antMatchers(webConsoleUrl + "/**").hasRole("ADMIN")
        .and()
         .httpBasic();
    }
```
by
```java
protected void configure(HttpSecurity http) throws Exception {
  LOGGER.info("Securing the webconsole access as property 'ff4j.webconsole.secure' is true");
  http.authorizeRequests()
        .antMatchers("/").permitAll()
        .antMatchers(webConsoleUrl + "/**").hasRole("ADMIN")
        .and()
        .formLogin();
    }
```

now the logout is accessible with `/logout`

Actuallly i did the update in the code you can `git pull`

Note :*I noticed you are based in China. You should try version `1.8.7` because we introduced support of chinese.*
