### ISSUE TITLE
Requiring DynamoDB configuration to be set via properties file breaks runtime configuration

### ISSUE THREAD

**Issue by qmunke** [ff4j/ff4j#611]
I'd like to be able to configure the various DynamoDB store properties (in particular table name) via environment variables, but since the removal of the constructor which takes a table name (and the switch to properties file based config) this isn't possible.

This feels like a backwards step to me for a framework that is intended to allow you to control code behaviour at runtime!

A constructor which takes a Properties argument to override the one loaded from the classpath is a possible solution to this.

**Comment by clun** [comment]
Sure, we would merge a pull request in that direction.

**Comment by clun** [comment]
I added the following constructor, hope it copes with your needs, I have a limited capabilities of tests without AWS account.

```java
 /**
     * Extension for configuration of the dynamo DB class.
     * @param client
     *      client Name
     * @param props
     *      properties
     * @param tableName
     *      tableName
     */
    public DynamoDBClient(DynamoDbClient client, Properties props, String tableName) {
        this.client          = client;
        this.dynamoDB        = DynamoDbEnhancedClient.builder().dynamoDbClient(client).build();
        this.persistentClass = (Class<STORE>) ((ParameterizedType) getClass()
                .getGenericSuperclass()).getActualTypeArguments()[1];
        loadProperties(props);
        if (tableName != null) {
            this.tableName = tableName;
        }
        table = dynamoDB.table(tableName, TableSchema.fromClass(persistentClass));
    }
```

**Comment by psoch** [comment]
Hey @clun, thanks for looking into this issue, but I'm not sure how to take advantage of your fix because `DynamoDBClient` is abstract and while I could create my own version of it I would also like to take advantage of all of the utilties in `FeatureDynamoDBClient`. Maybe I'm missing something, but do you have any recommendations for using environmental variables with ff4j? Ideally I'd like to use something like spring boot properties where I could either have an environmental profile or dynamically update property values at runtime, but this doesn't seem possible with ff4j since the file name is hardcoded and we can't add overrides in most places. Thank you!
